appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: CXSkuC1Har2bWDViZ/lOU1fbQXhrBaZp1cFooSObAcptlJsqQTzX6l4p7YiFuRIXy69/4UvnMhU7GGAT3DYNp2YcLgtIl4w43XJRA27xLpHx1P2HbR2UPCdmyxya4V+bWTtY7ejZk+si7lWe5rOUwrUCbbhMIBODXPNBzItb90bn1NKvOqrwsxKq+gto44yh1cOxZBzxyPmTzK21iPFfn3JHDvifAeINujbuIm6FIAQvMXyB/J7KXOW3sComMY/QUskkHwQaM9TzW6Dc4LWmTUYIgGxtXP7QhKdSOUk78JLsuTd/GFs7CYj4H1a7WjEje2mzP+VpjPIhyj34ZXSHV6Vdjhy/LeXFNw3dzmBEYQWTpc7ixyZ/E/wm6YvaGLiPgp2yGZIxxJt/yinlHuUgjmVnjn9koEkKw08CMoT5d1UlyjNmTVuD29QYMjKWomtntXRe7srorMjiWnRmObAQy22rqjOgcnC42Kk5Z3HxA+kNO9eIC6VmhCdiB7LGEEc/elr2jY/i7nfxRjC5qoCVNp0gIt2PUUv3ACHkShJfSfIXe4j8Liu6hA1DOqRWyy0JqCccJ6+EX4fD/cuKOwjGSNeE3gtb7UUXnoSWmQttcQJgBvZ3IO6OPOGkcDvmqiZwgjD+zQT9iu+1RzIH1FiQKODHxlT7pIpFQK46Z3ZENbI=
